category:
  - "連鎖飲食"
  - "便利商店"
  - "銀行費用"
  - "生活服務"
  - "電子商務"
  - "百貨量販"
  - "保險費用"

sub_category:
  - "早午餐"
  - "快速主餐"
  - "手搖飲"
  - "烘焙點心"
  - "在地飲食"
  - "公共事業繳費"
  - "自動加值"
  - "交通服務"
  - "文創娛樂"
  - "家居設計"
  - "生活美妝"
  - "服飾"
  - "文具書本"
  - "3C耗材"
  - "便利商店"
  - "預付兌換"
  - "訂閱費"
  - "壽險"
  

ec_platform_type:
  - "Saas" 
  - "RetailEC"
  - "DigitalDistribution"
  - "O2O 服務"

  
